# Generated by Django 2.2 on 2019-04-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='info',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
